#!/usr/bin/env bash
# Creates the four pre-existing Kubernetes Secrets the app chart
# requires (helm/nexus-scheduler — see values.yaml's `secrets:` block
# and the NOTES.txt checklist), with formats the apps actually accept:
#
#   nexus-scheduler-app         SESSION_SECRET          >= 32 chars
#                               API_KEY_ENCRYPTION_KEY  >= 32 chars
#                               BOOTSTRAP_ADMIN_EMAIL   valid email
#                               BOOTSTRAP_ADMIN_PASSWORD >= 12 chars
#   nexus-scheduler-oidc        OIDC_CLIENT_SECRET      (placeholder)
#   nexus-scheduler-postgresql  username, password, database
#   nexus-scheduler-redis       password
#
# The length floors are enforced by the api/worker's own config
# validation (packages/api/src/config.ts, packages/worker/src/config.ts)
# — a too-short value doesn't degrade, it crashloops the pod with
# "Invalid environment configuration". Both env secrets are envFrom'd
# unconditionally, so all four must exist before install even if OIDC
# stays disabled (a missing Secret is a CreateContainerConfigError).
#
# DEV CLUSTERS ONLY. Production secrets come from your platform's secret
# management (REQUIREMENTS §9.1: never generated by the chart, never in
# images) — do not point this script at a real cluster. Idempotent:
# re-running regenerates every secret (kubectl apply), so run it once
# per cluster, before `helm install`.
#
# Usage: scripts/create-dev-secrets.sh [namespace]
set -euo pipefail

NAMESPACE="${1:-$(kubectl config view --minify -o jsonpath='{..namespace}')}"
NAMESPACE="${NAMESPACE:-default}"

rand() { openssl rand -hex "$1"; }

ADMIN_PASSWORD="$(rand 8)" # 16 chars, floor is 12

apply() {
  # create --dry-run | apply = idempotent create-or-update
  kubectl create secret generic "$@" \
    --namespace "$NAMESPACE" --dry-run=client -o yaml | kubectl apply -f -
}

apply nexus-scheduler-app \
  --from-literal=SESSION_SECRET="$(rand 24)" \
  --from-literal=API_KEY_ENCRYPTION_KEY="$(rand 24)" \
  --from-literal=BOOTSTRAP_ADMIN_EMAIL="admin@nexus-scheduler.local" \
  --from-literal=BOOTSTRAP_ADMIN_PASSWORD="$ADMIN_PASSWORD"

# Placeholder so the envFrom secretRef resolves with OIDC disabled
# (oidc.enabled=false, the default). When enabling OIDC, replace it with
# the client secret issued by your identity provider.
apply nexus-scheduler-oidc \
  --from-literal=OIDC_CLIENT_SECRET="dev-placeholder-not-a-real-secret"

apply nexus-scheduler-postgresql \
  --from-literal=username="nexus" \
  --from-literal=password="$(rand 16)" \
  --from-literal=database="nexus"

apply nexus-scheduler-redis \
  --from-literal=password="$(rand 16)"

echo
echo "Secrets created in namespace '$NAMESPACE'."
echo "Break-glass admin login: admin@nexus-scheduler.local / $ADMIN_PASSWORD"
echo "(rotate by re-running this script and rolling the api Deployment)"
