#!/usr/bin/env bash
# Generates a local .env with randomly generated secrets for the Docker
# Compose dev/test stack (REQUIREMENTS.md §9.2 — "randomly generated
# keys for testing... no committed default passwords/keys"). Safe to
# re-run: it will not overwrite an existing .env.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists — leaving it as-is. Delete it first if you want fresh secrets."
  exit 0
fi

random_hex() {
  openssl rand -hex "$1"
}

cat > .env <<EOF
# Generated by scripts/generate-local-env.sh — local Compose use only.
# Never commit this file (it's in .gitignore) and never reuse these
# values outside local dev/testing.

POSTGRES_DB=nexus_scheduler
POSTGRES_USER=nexus
POSTGRES_PASSWORD=$(random_hex 24)

REDIS_PASSWORD=$(random_hex 24)

SESSION_SECRET=$(random_hex 32)
API_KEY_ENCRYPTION_KEY=$(random_hex 32)

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=$(random_hex 16)

# Built-in break-glass admin (REQUIREMENTS §4) — this env var is the
# ongoing source of truth for its password, re-synced on every API
# startup, not just a one-time seed.
BOOTSTRAP_ADMIN_EMAIL=admin@nexus-scheduler.local
BOOTSTRAP_ADMIN_PASSWORD=$(random_hex 16)

LIBRECHAT_BASE_URL=http://host.docker.internal:3080
EOF

echo "Wrote .env with freshly generated local secrets."
echo "Built-in admin: BOOTSTRAP_ADMIN_EMAIL / BOOTSTRAP_ADMIN_PASSWORD in .env"
